version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/sharon/Around
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t suemay0427/around .
          docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
          docker push your-dockerHub-user/around
